### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by Uberoverlord** [markasoftware/key4key#3]
The website logs IPs and stores keys in plain text. Until these issues are resolved I cannot use this service.

**Comment by markasoftware** [comment]
I'm unclear what the "security concern" is. Nginx, the most popular webserver software in the world, not only logs IP addresses but also user agents along with URLs, all *by default*. On any website that includes a username in the URL, that is enough information for the website owner to discover the IP addresses per username. Key4Key does not put usernames in the URL, so this is the alternative.

You also mentioned on Discord already that you do not wish to join for other reasons, so I am skeptical of the statement "Until these issues are resolved I cannot use this service".

I also doubt you would want to use this service if it was riddled with swarm members, which is the alternative.

**Comment by NuIIUC** [comment]
Its riddled with swarm members regardless
